name: Trigger auto deployment for hello-mgu

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Lab_6/App/**'
    - '.github/workflows/hello-mgu-AutoDeployTrigger-97bce32c-d37a-4769-b73b-23d360f7d0a7.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrlab6mgu.azurecr.io
          username: ${{ secrets.HELLOMGU_REGISTRY_USERNAME }}
          password: ${{ secrets.HELLOMGU_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrlab6mgu.azurecr.io/hello-mgu:${{ github.sha }}
          file: ./Lab_6/App/Dockerfile
          context: ./Lab_6/App/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLOMGU_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n hello-mgu -g RG-Lab6-MGU --server acrlab6mgu.azurecr.io --username  ${{ secrets.HELLOMGU_REGISTRY_USERNAME }} --password ${{ secrets.HELLOMGU_REGISTRY_PASSWORD }}
            az containerapp update -n hello-mgu -g RG-Lab6-MGU --image acrlab6mgu.azurecr.io/hello-mgu:${{ github.sha }}
